version: '3.9'

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    user: root
    volumes:
      - .:/app
    command: >
      bash -c "
        if [ -f convert_markdown_to_rasa.py ]; then
          pip install python-frontmatter &&
          python convert_markdown_to_rasa.py;
        fi &&
        rasa run --enable-api --debug
      "

  rasa-shell:
    build: .
    user: root
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    entrypoint: >
      bash -c "
        if [ -f convert_markdown_to_rasa.py ]; then
          pip install python-frontmatter &&
          python convert_markdown_to_rasa.py;
        fi &&
        rasa shell
      "

  rasa-train:
    build: .
    user: root
    volumes:
      - .:/app
    entrypoint: >
      bash -c "
        if [ -f convert_markdown_to_rasa.py ]; then
          pip install python-frontmatter &&
          python convert_markdown_to_rasa.py;
        fi &&
        rasa train
      "
