version: '3.9'

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    user: root
    volumes:
      - .:/app
    command: >
      bash -c "
        pip install python-frontmatter &&
        python convert_markdown_to_rasa.py &&
        rasa run --enable-api --debug
      "

  rasa-shell:
    build: .
    user: root
    volumes:
      - .:/app
    entrypoint: >
      bash -c "
        pip install python-frontmatter &&
        python convert_markdown_to_rasa.py &&
        rasa shell
      "
